const text = [
  "Zombie ipsum actually everyday carry plaid keffiyeh blue bottle wolf quinoa squid four loko glossier kinfolk woke. Plaid cliche cloud bread wolf, etsy humblebrag ennui organic fixie. Tousled sriracha vice VHS. Chillwave vape raw denim aesthetic flannel paleo, austin mixtape lo-fi next level copper mug +1 cred before they sold out. Prism pabst raclette gastropub.",
  "Activated charcoal jean shorts portland vice hashtag brooklyn blog art party meditation drinking vinegar chartreuse. Sriracha normcore you probably haven't heard of them VHS keytar cloud bread williamsburg adaptogen portland salvia neutra vice poke marfa authentic. Semiotics keytar unicorn readymade direct trade next level williamsburg vice before they sold out. Kogi shabby chic chambray snackwave vinyl franzen kombucha hammock glossier wayfarers hexagon umami. Vexillologist unicorn dreamcatcher hashtag enamel pin readymade polaroid tbh man bun small batch selfies sustainable.",
  "Asymmetrical palo santo bushwick shabby chic, lumbersexual raw denim gentrify swag banh mi +1 messenger bag mumblecore gochujang hammock synth. Seitan chicharrones ennui intelligentsia brunch coloring book jean shorts squid cloud bread williamsburg post-ironic iPhone try-hard hella. Twee authentic vaporware beard marfa try-hard truffaut raw denim 8-bit slow-carb. Hell of trust fund art party letterpress glossier bicycle rights. Shoreditch helvetica raclette wayfarers crucifix shabby chic.",
  "Tattooed deep v hoodie chia keffiyeh bitters. 3 wolf moon mixtape small batch health goth forage, listicle ethical austin. Quinoa man braid pitchfork, brunch direct trade shaman post-ironic heirloom williamsburg helvetica everyday carry. Locavore yr umami, sartorial hoodie hella copper mug tumblr hexagon quinoa. Lomo tumblr fanny pack ennui. Shaman iceland thundercats offal migas.",
  "Cornhole sartorial helvetica snackwave. Health goth flannel tattooed ethical live-edge brunch. Deep v mustache four loko, selfies letterpress biodiesel chillwave ramps cold-pressed occupy next level fanny pack taxidermy four dollar toast. Craft beer pitchfork raclette ugh fingerstache portland. Subway tile shoreditch 3 wolf moon vape hoodie. Four dollar toast stumptown VHS vice jianbing.",
  "Fingerstache sartorial pop-up normcore bicycle rights aesthetic enamel pin tattooed letterpress plaid kickstarter. Church-key pug offal, tattooed chartreuse taxidermy kinfolk williamsburg art party brooklyn slow-carb. Raw denim master cleanse semiotics celiac squid, vexillologist cardigan organic copper mug af. Tacos wolf paleo, vegan chillwave aesthetic YOLO sartorial meggings sriracha woke vice neutra. Forage bespoke green juice deep v semiotics meditation vinyl, next level cornhole street art wayfarers venmo.",
  "Pinterest stumptown artisan +1 brooklyn four dollar toast forage YOLO before they sold out. Seitan mlkshk raclette twee portland iPhone biodiesel activated charcoal migas sartorial occupy. Poke synth fanny pack kale chips squid pabst wolf coloring book aesthetic raclette. Roof party kinfolk try-hard, swag marfa offal disrupt meh af green juice retro meggings gochujang echo park letterpress. Cronut godard forage twee blog ennui.",
  "Direct trade poutine sartorial drinking vinegar vaporware raclette humblebrag cliche lomo vape godard DIY kale chips cloud bread ethical. Tousled heirloom lumbersexual kitsch scenester aesthetic sriracha jean shorts squid readymade wayfarers. Waistcoat copper mug cardigan gluten-free. Shoreditch iceland you probably haven't heard of them irony yuccie yr umami taxidermy fashion axe tattooed craft beer beard hashtag four loko hot chicken. Direct trade sriracha vegan, venmo four dollar toast semiotics mixtape crucifix air plant glossier VHS hot chicken. Fanny pack gluten-free narwhal seitan.",
];

export default text;
